### ISSUE TITLE
new RabbitExchangeQueueProvisioner throws IllegalAccessError

### ISSUE THREAD

**Issue by marvinrichter** [spring-cloud/spring-cloud-stream-binder-rabbit#46]
The new RabbitExchangeQueueProvisioner introduced with d9c4044 breaks the application startup because it's trying to instantiate an ExhangeBuilder.

It should either use one of the ExchangeBuilders factory methods or create an exchange on it's own.

```
Caused by: java.lang.IllegalAccessError: tried to access method org.springframework.amqp.core.ExchangeBuilder.<init>(Ljava/lang/String;Ljava/lang/String;)V from class org.springframework.cloud.stream.binder.rabbit.provisioning.RabbitExchangeQueueProvisioner
	at org.springframework.cloud.stream.binder.rabbit.provisioning.RabbitExchangeQueueProvisioner.buildExchange(RabbitExchangeQueueProvisioner.java:392) ~[spring-cloud-stream-binder-rabbit-core-1.2.0.BUILD-20170214.185532-3.jar:1.2.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binder.rabbit.provisioning.RabbitExchangeQueueProvisioner.provisionProducerDestination(RabbitExchangeQueueProvisioner.java:87) ~[spring-cloud-stream-binder-rabbit-core-1.2.0.BUILD-20170214.185532-3.jar:1.2.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binder.rabbit.provisioning.RabbitExchangeQueueProvisioner.provisionProducerDestination(RabbitExchangeQueueProvisioner.java:57) ~[spring-cloud-stream-binder-rabbit-core-1.2.0.BUILD-20170214.185532-3.jar:1.2.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:112) ~[spring-cloud-stream-1.2.0.BUILD-20170214.181238-31.jar:1.2.0.BUILD-SNAPSHOT]
```

**Comment by marvinrichter** [comment]
Never mind, had the wrong spring-boot-parent which pulled in the wrong version of spring-amqp
