### ISSUE TITLE
Issue with durable with latest spring boot

### ISSUE THREAD

**Issue by BLaurent** [spring-cloud/spring-cloud-stream-binder-rabbit#62]
Hi,

I am trying to use reactive components:

>     <parent>
>         <groupId>org.springframework.boot</groupId>
>         <artifactId>spring-boot-starter-parent</artifactId>
>         <version>2.0.0.BUILD-SNAPSHOT</version>
>         <relativePath/>
>     </parent>
> 

```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-stream-rabbit</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-reactive</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>spring-boot-starter-web</artifactId>
                    <groupId>org.springframework.boot</groupId>
                </exclusion>
            </exclusions>
        </dependency>
```

But When running the method"
```
    @InboundChannelAdapter(value = Source.OUTPUT, poller = @Poller(fixedDelay = "${fixedDelay}", maxMessagesPerPoll = "1"))
    public MessageSource<String> timerMessageSource() {
        return () -> new GenericMessage<>(new SimpleDateFormat(this.format).format(new Date()));
    }
```

I end up having this: 

```
> org.springframework.context.ApplicationContextException: Failed to start bean 'outputBindingLifecycle'; nested exception is java.lang.NoSuchMethodError: org.springframework.amqp.core.ExchangeBuilder.durable()Lorg/springframework/amqp/core/ExchangeBuilder;
> 	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-5.0.0.BUILD-20170405.202452-68.jar:5.0.0.BUILD-SNAPSHOT]
> 	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50) ~[spring-context-5.0.0.BUILD-20170405.202452-68.jar:5.0.0.BUILD-SNAPSHOT]
> 	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348) ~[spring-context-5.0.0.BUILD-20170405.202452-68.jar:5.0.0.BUILD-SNAPSHOT]
> 	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151) ~[spring-context-5.0.0.BUILD-20170405.202452-68.jar:5.0.0.BUILD-SNAPSHOT]
> 	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114) ~[spring-context-5.0.0.BUILD-20170405.202452-68.jar:5.0.0.BUILD-SNAPSHOT]
> 	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:881) ~[spring-context-5.0.0.BUILD-20170405.202452-68.jar:5.0.0.BUILD-SNAPSHOT]
> 	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.finishRefresh(ReactiveWebServerApplicationContext.java:71) ~[spring-boot-2.0.0.BUILD-20170405.153845-500.jar:2.0.0.BUILD-SNAPSHOT]
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544) ~[spring-context-5.0.0.BUILD-20170405.202452-68.jar:5.0.0.BUILD-SNAPSHOT]
> 	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:49) ~[spring-boot-2.0.0.BUILD-20170405.153845-500.jar:2.0.0.BUILD-SNAPSHOT]
> 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:809) [spring-boot-2.0.0.BUILD-20170405.153845-500.jar:2.0.0.BUILD-SNAPSHOT]
> 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:404) [spring-boot-2.0.0.BUILD-20170405.153845-500.jar:2.0.0.BUILD-SNAPSHOT]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:347) [spring-boot-2.0.0.BUILD-20170405.153845-500.jar:2.0.0.BUILD-SNAPSHOT]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1263) [spring-boot-2.0.0.BUILD-20170405.153845-500.jar:2.0.0.BUILD-SNAPSHOT]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1252) [spring-boot-2.0.0.BUILD-20170405.153845-500.jar:2.0.0.BUILD-SNAPSHOT]
> 	at com.ge.digital.HttpSensorsIngesterApplication.main(HttpSensorsIngesterApplication.java:11) [classes/:na]
> Caused by: java.lang.NoSuchMethodError: org.springframework.amqp.core.ExchangeBuilder.durable()Lorg/springframework/amqp/core/ExchangeBuilder;
> 	at org.springframework.cloud.stream.binder.rabbit.provisioning.RabbitExchangeQueueProvisioner.buildExchange(RabbitExchangeQueueProvisioner.java:395) ~[spring-cloud-stream-binder-rabbit-core-1.2.1.BUILD-20170404.203757-1.jar:1.2.1.BUILD-SNAPSHOT]
> 	at org.springframework.cloud.stream.binder.rabbit.provisioning.RabbitExchangeQueueProvisioner.provisionProducerDestination(RabbitExchangeQueueProvisioner.java:88) ~[spring-cloud-stream-binder-rabbit-core-1.2.1.BUILD-20170404.203757-1.jar:1.2.1.BUILD-SNAPSHOT]
> 	at org.springframework.cloud.stream.binder.rabbit.provisioning.RabbitExchangeQueueProvisioner.provisionProducerDestination(RabbitExchangeQueueProvisioner.java:58) ~[spring-cloud-stream-binder-rabbit-core-1.2.1.BUILD-20170404.203757-1.jar:1.2.1.BUILD-SNAPSHOT]
> 	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:108) ~[spring-cloud-stream-1.2.1.BUILD-20170404.192519-1.jar:1.2.1.BUILD-SNAPSHOT]
> 	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:55) ~[spring-cloud-stream-1.2.1.BUILD-20170404.192519-1.jar:1.2.1.BUILD-SNAPSHOT]
> 	at org.springframework.cloud.stream.binder.AbstractBinder.bindProducer(AbstractBinder.java:152) ~[spring-cloud-stream-1.2.1.BUILD-20170404.192519-1.jar:1.2.1.BUILD-SNAPSHOT]
> 	at org.springframework.cloud.stream.binding.BindingService.bindProducer(BindingService.java:125) ~[spring-cloud-stream-1.2.1.BUILD-20170404.192519-1.jar:1.2.1.BUILD-SNAPSHOT]
> 	at org.springframework.cloud.stream.binding.BindableProxyFactory.bindOutputs(BindableProxyFactory.java:238) ~[spring-cloud-stream-1.2.1.BUILD-20170404.192519-1.jar:1.2.1.BUILD-SNAPSHOT]
> 	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.start(OutputBindingLifecycle.java:57) ~[spring-cloud-stream-1.2.1.BUILD-20170404.192519-1.jar:1.2.1.BUILD-SNAPSHOT]
> 	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:175) ~[spring-context-5.0.0.BUILD-20170405.202452-68.jar:5.0.0.BUILD-SNAPSHOT]
> 	... 14 common frames omitted
> 
```

I can work of this but I might need a little help.

Thanks in advance
Regards

**Comment by artembilan** [comment]
```
> at org.springframework.boot.SpringApplication.run(SpringApplication.java:1252) [spring-boot-2.0.0.BUILD-20170405.153845-500.jar:2.0.0.BUILD-SNAPSHOT]
...
> Caused by: java.lang.NoSuchMethodError: org.springframework.amqp.core.ExchangeBuilder.durable()Lorg/springframework/amqp/core/ExchangeBuilder;
```
This project doesn't claim to be compatible with Spring Boot `2.0.0`.
Please, use the latest stable - `1.5.2`

**Comment by mbogoevici** [comment]
Closing as per @artembilan answer. When using WebFlux, the Elmhurst release train will support Boot 2.
